# ============================================================
# Queries SQL para dashboard SETIEPS-EPS
# Ajusta nombres de columnas si tu base usa nombres distintos.
# ============================================================

QUERY_Q4 = """
WITH Q4_BASE AS (
    SELECT
        P.RUCPRESTADOR_CRYPTO AS IPRESS_ORIGINAL,
        COUNT(P.NUMEXPEDIENTELIQUI_CRYPTO) AS TOTAL_PRESTACIONES,
        SUM(G.TOTALLIQUIDADOSIN_IGV) AS TOTAL_LIQUIDADO_SIN_IGV
    FROM PRESTACION AS P
    INNER JOIN GASTO AS G
        ON P.NUMEXPEDIENTELIQUI_CRYPTO = G.NUMEXPEDIENTELIQUI_CRYPTO
    GROUP BY P.RUCPRESTADOR_CRYPTO
),
Q4_NUMERADO AS (
    SELECT
        'IPRESS ' + CAST(
            ROW_NUMBER() OVER (
                ORDER BY TOTAL_LIQUIDADO_SIN_IGV DESC
            ) AS VARCHAR(10)
        ) AS IPRESS,
        IPRESS_ORIGINAL,
        TOTAL_PRESTACIONES,
        TOTAL_LIQUIDADO_SIN_IGV
    FROM Q4_BASE
)
SELECT
    IPRESS,
    IPRESS_ORIGINAL,
    TOTAL_PRESTACIONES,
    TOTAL_LIQUIDADO_SIN_IGV
FROM Q4_NUMERADO
ORDER BY TOTAL_LIQUIDADO_SIN_IGV DESC;
"""

QUERY_Q19 = """
WITH GastoDiario AS (
    SELECT
        CAST(P.FECHAINICIOPRESTACION AS DATE) AS FECHA_PRESTACION,
        COUNT(P.NUMEXPEDIENTELIQUI_CRYPTO) AS TOTAL_PRESTACIONES_DIA,
        SUM(G.TOTALLIQUIDADOSIN_IGV) AS TOTAL_LIQUIDADO_DIA
    FROM PRESTACION AS P
    INNER JOIN GASTO AS G
        ON P.NUMEXPEDIENTELIQUI_CRYPTO = G.NUMEXPEDIENTELIQUI_CRYPTO
    WHERE P.FECHAINICIOPRESTACION IS NOT NULL
    GROUP BY CAST(P.FECHAINICIOPRESTACION AS DATE)
)
SELECT
    FECHA_PRESTACION,
    TOTAL_PRESTACIONES_DIA,
    TOTAL_LIQUIDADO_DIA,
    SUM(TOTAL_LIQUIDADO_DIA) OVER (
        ORDER BY FECHA_PRESTACION
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS LIQUIDADO_ACUMULADO
FROM GastoDiario
ORDER BY FECHA_PRESTACION;
"""

QUERY_Q24 = """
DECLARE @Anio_Analisis INT = 2026;

-- Cambiar a 0 si se desea excluir la cobertura "No corresponde"
DECLARE @Incluir_Cobertura_Cero BIT = 1;

WITH BaseGasto AS (
    SELECT
        C.CODIGOCOBERTURA,
        C.DESCRIPCION AS COBERTURA,
        YEAR(P.FECHAINICIOPRESTACION) AS ANIO,

        ISNULL(G.GASTOHONORARIOPROC, 0) AS HONORARIOS_MEDICOS,
        ISNULL(G.GASTOFARMACIA, 0) AS FARMACIA,
        ISNULL(G.GASTOSERVCLINICO, 0) AS SERVICIOS_CLINICOS,
        ISNULL(G.GASTOEXLAB, 0) AS EXAMENES_LABORATORIO,
        ISNULL(G.GASTOEXIMAG, 0) AS EXAMENES_IMAGEN,
        ISNULL(G.GASTOOTROS, 0) AS OTROS_GASTOS

    FROM PRESTACION AS P

    INNER JOIN COBERTURA AS C
        ON P.CODIGOCOBERTURA = C.CODIGOCOBERTURA

    INNER JOIN GASTO AS G
        ON P.NUMEXPEDIENTELIQUI_CRYPTO = G.NUMEXPEDIENTELIQUI_CRYPTO

    WHERE P.CODIGOCOBERTURA IS NOT NULL
      AND P.FECHAINICIOPRESTACION IS NOT NULL
      AND YEAR(P.FECHAINICIOPRESTACION) = @Anio_Analisis
      AND (
            @Incluir_Cobertura_Cero = 1
            OR C.CODIGOCOBERTURA <> 0
          )
),

GastoLargo AS (
    SELECT
        CODIGOCOBERTURA,
        COBERTURA,
        ANIO,
        COMPONENTE_GASTO,
        MONTO_COMPONENTE
    FROM BaseGasto

    UNPIVOT (
        MONTO_COMPONENTE FOR COMPONENTE_GASTO IN (
            HONORARIOS_MEDICOS,
            FARMACIA,
            SERVICIOS_CLINICOS,
            EXAMENES_LABORATORIO,
            EXAMENES_IMAGEN,
            OTROS_GASTOS
        )
    ) AS U
),

ResumenGasto AS (
    SELECT
        CODIGOCOBERTURA,
        COBERTURA,
        ANIO,
        COMPONENTE_GASTO,
        SUM(MONTO_COMPONENTE) AS MONTO_COMPONENTE
    FROM GastoLargo
    GROUP BY
        CODIGOCOBERTURA,
        COBERTURA,
        ANIO,
        COMPONENTE_GASTO
),

MetricasFinales AS (
    SELECT
        CODIGOCOBERTURA,
        COBERTURA,
        ANIO,
        COMPONENTE_GASTO,
        MONTO_COMPONENTE,

        CAST(
            ROUND(
                100.0 * MONTO_COMPONENTE /
                NULLIF(
                    SUM(MONTO_COMPONENTE) OVER (
                        PARTITION BY CODIGOCOBERTURA, ANIO
                    ),
                    0
                ),
                2
            ) AS DECIMAL(10, 2)
        ) AS PORC_PARTICIPACION,

        ROW_NUMBER() OVER (
            PARTITION BY CODIGOCOBERTURA, ANIO
            ORDER BY MONTO_COMPONENTE DESC, COMPONENTE_GASTO
        ) AS POSICION_EN_COBERTURA

    FROM ResumenGasto
)

SELECT
    CODIGOCOBERTURA,
    COBERTURA,
    ANIO,

    CASE COMPONENTE_GASTO
        WHEN 'HONORARIOS_MEDICOS' THEN 'Honorarios Médicos'
        WHEN 'FARMACIA' THEN 'Farmacia'
        WHEN 'SERVICIOS_CLINICOS' THEN 'Servicios Clínicos'
        WHEN 'EXAMENES_LABORATORIO' THEN 'Exámenes de Laboratorio'
        WHEN 'EXAMENES_IMAGEN' THEN 'Exámenes de Imagen'
        WHEN 'OTROS_GASTOS' THEN 'Otros Gastos'
        ELSE COMPONENTE_GASTO
    END AS COMPONENTE_GASTO,

    CAST(MONTO_COMPONENTE AS DECIMAL(18, 2)) AS MONTO_COMPONENTE,
    PORC_PARTICIPACION,
    POSICION_EN_COBERTURA

FROM MetricasFinales

ORDER BY
    CODIGOCOBERTURA,
    POSICION_EN_COBERTURA;
"""

QUERY_Q13 = """
WITH DIAGNOSTICOS_PREVALENTES AS (
    SELECT value AS CODCIE10
    FROM   STRING_SPLIT('J00,J06,K29,I10,E11,A09,J11,Z00,J18,K21', ',')
),
METRICAS_DIAGNOSTICO AS (
    SELECT
        P.CODCIE10,
        COUNT(P.NUMEXPEDIENTELIQUI_CRYPTO) AS TOTAL_PRESTACIONES,
        SUM(G.TOTALLIQUIDADOSIN_IGV)       AS TOTAL_LIQUIDADO,
        AVG(G.TOTALLIQUIDADOSIN_IGV)       AS PROMEDIO_LIQUIDADO
    FROM       PRESTACION AS P
    INNER JOIN GASTO      AS G
            ON P.NUMEXPEDIENTELIQUI_CRYPTO = G.NUMEXPEDIENTELIQUI_CRYPTO
    WHERE P.CODCIE10 IN (SELECT CODCIE10 FROM DIAGNOSTICOS_PREVALENTES)
    GROUP BY P.CODCIE10
)
SELECT
    CODCIE10,
    TOTAL_PRESTACIONES,
    TOTAL_LIQUIDADO,
    FORMAT(PROMEDIO_LIQUIDADO, 'N2') AS PROMEDIO_LIQUIDADO,
    CASE
        WHEN TOTAL_LIQUIDADO >= 400000 THEN 'ALTO IMPACTO'
        WHEN TOTAL_LIQUIDADO >= 100000 THEN 'IMPACTO MEDIO'
        ELSE                                'BAJO IMPACTO'
    END                              AS CLASIFICACION_IMPACTO,
    CONCAT_WS(' | ',
        CAST(TOTAL_PRESTACIONES AS VARCHAR) + ' prestaciones',
        'S/ ' + FORMAT(TOTAL_LIQUIDADO, 'N2') + ' liquidado'
    )                                AS RESUMEN_DIAGNOSTICO
FROM METRICAS_DIAGNOSTICO
ORDER BY
    CASE
        WHEN TOTAL_LIQUIDADO >= 400000 THEN 1
        WHEN TOTAL_LIQUIDADO >= 100000 THEN 2
        ELSE                                3
    END,
    TOTAL_LIQUIDADO DESC;
"""